### ISSUE TITLE
長期間実施中の TODO と未実施のものと区別できる。それによって実施中のものを優先的に進められる

### ISSUE THREAD

**Issue by ryounasso** [ryounasso/todo-app-by-clean-architecture#14]
## 受け入れ条件
- 実施中のマークをつけられる

**Comment by ryounasso** [comment]
進め方
- [ ] Statu table の追加
- [ ] Status を進める API
- [ ] list.json の返り値に status 追加
